apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: flask
  replicas: 2
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: isabelmacgill/hw3-kubernetes-docker-flask:latest2
        ports:
        - containerPort: 5000
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 20
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            scheme: HTTP
            path: /healthr
            port: 5000
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 20
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: /healthl
            port: 5000
        env:
        - name: MONGO_HOST
          value: mongodb://mongo:27017/dev
        - name: MONGO_PORT
          value: '27017'
        resources:
          limits:
            cpu: '1'
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
