version: "3.9"
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_HOST: mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
volumes:
  db-data:
